/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["submit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/demo/transactions/{id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["submitReview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/demo/replay/{scenarioId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["replay"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/demo/transactions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getTransactionStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/demo/transactions/{id}/detail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getTransactionDetail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/demo/scenarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listScenarios"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        SubmitTransactionRequest: {
            userExternalRef: string;
            deviceFingerprint: string;
            merchantName: string;
            merchantCategory?: string;
            amount: number;
            currency: string;
            /** Format: date-time */
            transactionTime?: string;
            locationCountry: string;
            locationCity: string;
            features: {
                [key: string]: unknown;
            };
        };
        ReplayAcceptedResult: {
            /** Format: int64 */
            transactionId?: number;
            /** @enum {string} */
            status?: "PENDING" | "SCORED";
        };
        SubmitReviewRequest: {
            /** @enum {string} */
            decision?: "APPROVED" | "REJECTED";
            note?: string;
        };
        AnalystReviewSummary: {
            /** @enum {string} */
            decision?: "APPROVED" | "REJECTED";
            note?: string;
            reviewedBy?: string;
            /** Format: date-time */
            reviewedAt?: string;
        };
        LoginRequest: {
            username?: string;
            password?: string;
        };
        LoginResponse: {
            token?: string;
        };
        TransactionStatusResult: {
            /** Format: int64 */
            transactionId?: number;
            /** @enum {string} */
            status?: "PENDING" | "SCORED";
            fraudProbability?: number;
            /** @enum {string} */
            action?: "APPROVE" | "REVIEW" | "BLOCK";
            modelVersion?: string;
        };
        ShapContribution: {
            featureName?: string;
            featureValue?: string;
            shapValue?: number;
        };
        TransactionDetailResult: {
            /** Format: int64 */
            transactionId?: number;
            /** @enum {string} */
            status?: "PENDING" | "SCORED";
            amount?: number;
            currency?: string;
            /** Format: date-time */
            transactionTime?: string;
            locationCountry?: string;
            locationCity?: string;
            merchantName?: string;
            merchantCategory?: string;
            userExternalRef?: string;
            deviceFingerprint?: string;
            fraudProbability?: number;
            /** @enum {string} */
            mlAction?: "APPROVE" | "REVIEW" | "BLOCK";
            modelVersion?: string;
            baseValue?: number;
            shapContributions?: components["schemas"]["ShapContribution"][];
            /** @enum {string} */
            ruleAction?: "APPROVE" | "REVIEW" | "BLOCK";
            matchedRules?: string;
            /** @enum {string} */
            finalAction?: "APPROVE" | "REVIEW" | "BLOCK";
            analystReview?: components["schemas"]["AnalystReviewSummary"];
        };
        ScenarioSummary: {
            scenarioId?: string;
            label?: string;
            groundTruthIsFraud?: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    submit: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitTransactionRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ReplayAcceptedResult"];
                };
            };
        };
    };
    submitReview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitReviewRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AnalystReviewSummary"];
                };
            };
        };
    };
    replay: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenarioId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ReplayAcceptedResult"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LoginResponse"];
                };
            };
        };
    };
    getTransactionStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TransactionStatusResult"];
                };
            };
        };
    };
    getTransactionDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TransactionDetailResult"];
                };
            };
        };
    };
    listScenarios: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ScenarioSummary"][];
                };
            };
        };
    };
}
